name: rewind_words
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audio_recorder:
    git: git://github.com/mmcc007/audio_recorder.git
  audioplayers: ^0.7.8
  reverse_audio:
    path: ../reverse_audio

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true