name: rewind_words
description: Game app to have fun with reverse words.
version: 1.0.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audio_recorder:
    git: git://github.com/Pyozer/audio_recorder
  audioplayers: ^0.7.8
  reverse_audio:
    git: git://github.com/Pyozer/reverse_audio
  path_provider: ^0.4.1
  simple_permissions: ^0.1.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
  
flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_background: "#835BEA"
  adaptive_icon_foreground: "assets/images/ic_launcher_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
     - family: JandaSafeandSound
       fonts:
          - asset: assets/fonts/JandaSafeandSound.ttf
            style: normal

     - family: palameciaTitling
       fonts:
          - asset: assets/fonts/palameciaTitling.ttf
            style: normal
